sabzweb/blog/urls.py
from django.urls import path,include
from . import views
from django.contrib.auth import views as auth_views
from .forms import LoginForm
app_name = "blog"



urlpatterns = [
    path('', views.index, name="index"),
    path('posts/', views.post_list, name="post_list"),
    path('posts/<str:category>', views.post_list, name="post_list_category"),
    # path('posts/', views.PostListView.as_view(), name="post_list"),
    # path('posts/<int:id>', views.post_detail, name="post_detail"),
    path('posts/detail/<pk>', views.post_detail, name="post_detail"),
    path('posts/<post_id>/comment', views.post_comment, name="post_comment"),
    path('ticket/', views.ticket, name="ticket"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name="profile"),
    path('profile/create_post', views.create_post, name="create_post"),
    path('profile/create_post/<post_id>', views.edit_post, name="edit_post"),
    path('profile/delete_post/<post_id>', views.delete_post, name="delete_post"),
    path('profile/delete_image/<image_id>', views.delete_image, name="delete_image"),
    # path('login/', views.login,name="login"),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm), name="login"),
    # path('logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('logout/', views.log_out, name="logout"),

    path('password-change/', auth_views.PasswordChangeView.as_view(success_url='done'), name="password_change"),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name="password_change_done"),

    path('password-reset/', auth_views.PasswordResetView.as_view(success_url='done'), name="password_reset"),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name="password_reset_done"),
    path('password-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(success_url='/blog/password-reset/complete'), name="password_reset_confirm"),
    path('password-reset/complete/',auth_views.PasswordResetCompleteView.as_view(), name="password_reset_complete"),

    path('register/', views.register, name="register"),
    path('account/edit', views.edit_account, name="edit_account"),
    path('markdownx/', include('markdownx.urls')),
]

sabzweb/sabzweb/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog"))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

sabzweb/blog/forms.py
from cProfile import label

from django import forms
from .models import Comment, Post, User, Account
from django.contrib.auth.forms import AuthenticationForm

class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True)
    name = forms.CharField(max_length=250, required=True)
    email = forms.EmailField()
    phone = forms.CharField(max_length=11, required=True)
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError("شماره تلفن عددی نیست!")
            else:
                return phone


class CommentForm(forms.ModelForm):
    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError("نام کوتاه است")
            else:
                return name

    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets={
            'body': forms.TextInput(attrs={
                'placeholder': 'متن',
                'class':'form-control'
            }),
            'name': forms.TextInput(attrs={
                'placeholder': 'نام',
                'class': 'form-control'
            }),
        }

class SearchForm(forms.Form):
    query = forms.CharField()

class CreatePostForm(forms.ModelForm):
    image1 = forms.ImageField(label="تصویر اول", widget=forms.FileInput(attrs={'class': 'form-control'}))
    image2 = forms.ImageField(label="تصویر دوم", widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets={
            'title': forms.TextInput(attrs={
                'class':'form-control',
                'id' : "con-name",

            }),
            'description': forms.Textarea(attrs={
            	'class': 'form-control',
				 'rows': '5',
            }),
            'reading_time': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'category': forms.Select(attrs={
                'class': 'form-select',
            }),


        }


class LoginForm(AuthenticationForm):
    username = forms.CharField(max_length=250, required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(max_length=250, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control'}))


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput(attrs={'class': 'form-control'}), label='تکرار پسورد')
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name' , 'email']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
        }
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسورد ها مطابقت ندارند!')
        return cd['password2']

class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']
        widgets = {
            'first_name': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'last_name': forms.TextInput(attrs={
                'class': 'form-control',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
            }),
        }

class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']
        widgets = {
            'date_of_birth': forms.DateInput(attrs={
                'class': 'form-control',
            }),
            'bio': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': '5',
            }),
            'job': forms.TextInput(attrs={
                'class': 'form-control',

            }),
            'photo': forms.FileInput(attrs={
                'class': 'form-control',
            }),
        }

sabzweb/blog/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404
from .models import *
from .forms import *
from django.views.generic import ListView, DetailView
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

def index(request):
    last_post = Post.published.all().order_by('-publish')[0]
    return render(request, "blog/index.html", {"last_post": last_post})

def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    
    context = {
        'posts': posts,
        'category': category
    }
    return render(request, "blog/list.html", context)

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 4
    template_name = "blog/list.html"

def post_detail(request, pk):
    post = get_object_or_404(Post, id=pk, status=Post.Status.PUBLISHED)
    comments = post.comments.filter(active=True)
    form = CommentForm()
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, "blog/detail.html", context)

def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(
                message=cd['message'],
                name=cd['name'],
                email=cd['email'],
                phone=cd['phone'],
                subject=cd['subject']
            )
            return redirect("blog:index")
    else:
        form = TicketForm()
    return render(request, "forms/ticket.html", {'form': form})

@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {
        'post': post,
        'form': form,
        'comment': comment
    }
    return render(request, "forms/comment.html", context)

def post_search(request):
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(data=request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.published.filter(
                Q(title__icontains=query) | Q(description__icontains=query)
            ).distinct()
    context = {
        'query': query,
        'results': results
    }
    return render(request, 'blog/search.html', context)

@login_required
def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)
    return render(request, 'blog/profile.html', {'posts': posts})

@login_required
def create_post(request):
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm()
    return render(request, 'forms/create-post.html', {'form': form})

@login_required
def delete_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/delete-post.html', {'post': post})

@login_required
def delete_image(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')

@login_required
def edit_post(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = CreatePostForm(instance=post)
    return render(request, 'forms/create-post.html', {'form': form, 'post': post})

def log_out(request):
    logout(request)
    return redirect('blog:index')  # به صفحه اصلی هدایت کنید

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password'])
            user.save()
            Account.objects.create(user=user)  # ایجاد حساب کاربری برای کاربر جدید
            return render(request, 'registration/register_done.html', {'user': user})
    else:
        form = UserRegisterForm()
    return render(request, 'registration/register.html', {'form': form})

@login_required
def edit_account(request):
    # بررسی وجود شیء Account برای کاربر
    if not hasattr(request.user, 'account'):
        # اگر حساب کاربری وجود ندارد، می‌توانید آن را ایجاد کنید
        Account.objects.create(user=request.user)

    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        account_form = AccountEditForm(request.POST, instance=request.user.account, files=request.FILES)
        if account_form.is_valid() and user_form.is_valid():
            account_form.save()
            user_form.save()
            return redirect('blog:profile')  # به صفحه پروفایل هدایت کنید
    else:
        user_form = UserEditForm(instance=request.user)
        account_form = AccountEditForm(instance=request.user.account)

    context = {
        'account_form': account_form,
        'user_form': user_form
    }
    return render(request, 'registration/edit_account.html', context)

sabzweb/blog/templates/partials/header.html
{% load static %}

<header class="border-bottom bg-dark text-white py-2">
  <nav class="container d-flex justify-content-between align-items-center flex-wrap">

    <!-- لوگو و عنوان برند -->
    <div class="d-flex align-items-center gap-3">
      <a href="{% url 'blog:index' %}" class="d-flex align-items-center text-white text-decoration-none">
        <img src="{% static 'images/icon/blog-logo.png' %}" alt="logo" height="36" class="me-2">
        <div class="d-flex flex-column">
          <span class="fw-bold fs-5">وبلاگ برنامه‌نویسی</span>
          <small class="text-light" style="font-size: 0.8rem;">با ما در دنیای کد بدرخشید</small>
        </div>
      </a>
    </div>

    <!-- منو و آیتم‌های بالایی -->
    <div class="d-flex align-items-center gap-3 flex-wrap">

      <!-- منو dropdown -->
      <div class="dropdown">
        <a class="btn btn-sm btn-outline-light dropdown-toggle" href="#" id="homeMenu" data-bs-toggle="dropdown">
          صفحات
        </a>
        <ul class="dropdown-menu dropdown-menu-dark">
          <li><a class="dropdown-item" href="{% url 'blog:index' %}">صفحه اصلی</a></li>
          <li><a class="dropdown-item" href="{% url 'blog:profile' %}">داشبورد</a></li>
          <li><a class="dropdown-item" href="{% url 'blog:post_list' %}">لیست مقالات</a></li>
        </ul>
      </div>

      <!-- جستجو -->
      <div class="dropdown">
        <a href="#" class="btn btn-sm btn-outline-light" data-bs-toggle="dropdown" aria-expanded="false">
          <i class="bi bi-search"></i>
        </a>
        <div class="dropdown-menu dropdown-menu-end p-2">
          <form method="get" action="{% url 'blog:post_search' %}">
            <div class="input-group">
              <input name="query" type="search" class="form-control" placeholder="جستجو">
              <button type="submit" class="btn btn-primary btn-sm">جستجو</button>
            </div>
          </form>
        </div>
      </div>

      <!-- سوئیچر تم -->
      <div class="dropdown">
        <button class="btn btn-sm btn-outline-light dropdown-toggle" id="bd-theme" data-bs-toggle="dropdown">
          <i class="bi bi-circle-half"></i>
        </button>
        <ul class="dropdown-menu dropdown-menu-dark">
          <li><button class="dropdown-item" type="button" data-bs-theme-value="light">روشن</button></li>
          <li><button class="dropdown-item" type="button" data-bs-theme-value="dark">تیره</button></li>
          <li><button class="dropdown-item" type="button" data-bs-theme-value="auto">خودکار</button></li>
        </ul>
      </div>

      <!-- کاربر یا ورود/ثبت‌نام -->
      {% if request.user.is_authenticated %}
        <a href="{% url 'blog:profile' %}" class="btn btn-sm btn-outline-success">
          {{ request.user.first_name|default:request.user.username }}
        </a>
      {% else %}
        <a href="{% url 'blog:login' %}" class="btn btn-sm btn-outline-light">ورود</a>
        <a href="{% url 'blog:register' %}" class="btn btn-sm btn-outline-light">ثبت‌نام</a>
      {% endif %}

    </div>

  </nav>
</header>

sabzweb/blog/templates/partials/latest_posts.html
{% load jformat %}

<div>
    <h2>آخرین پست‌ها</h2>
    {% for post in l_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }} : {{ post.publish|jformat:"%Y/%m/%d - %H:%M" }}
            </a>
        </p>
    {% endfor %}
</div>

sabzweb/blog/templates/partials/pagination.html
<div class="pagination"
{% if page.has_previous %}
  <a href="?page={{ page.previous_page_number }}">« Previous page</a>

  {% if page.number > 3 %}
    <a href="?page=1">1</a>
    {% if page.number > 4 %}
      <span>...</span>
    {% endif %}
  {% endif %}
{% endif %}

{% for num in page.paginator.page_range %}
  {% if page.number == num %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% elif num > page.number|add:'-3' and num < page.number|add:'3' %}
    <a href="?page={{ num }}">{{ num }}</a>
  {% endif %}
{% endfor %}

{% if page.has_next %}
  {% if page.number < page.paginator.num_pages|add:'-3' %}
    <span>...</span>
    <a href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a>
  {% elif page.number < page.paginator.num_pages|add:'-2' %}
    <a href="?page={{ page.paginator.num_pages }}">{{ page.paginator.num_pages }}</a>
  {% endif %}

  <a href="?page={{ page.next_page_number }}">Next Page »</a>
{% endif %}